// Generates src/theme/fonts.generated.css: Nunito latin subsets from @fontsource (woff2 only) plus
// the self-subsetted Japanese fonts in src/theme/fonts (see scripts/subset-fonts.py).
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const outFile = join(root, 'src/theme/fonts.generated.css');

let css = '/* GENERATED by scripts/fonts.mjs — do not edit. Run `npm run fonts`. */\n';

for (const w of [400, 600, 700, 800]) {
  const src = readFileSync(join(root, 'node_modules/@fontsource/nunito', `${w}.css`), 'utf8');
  for (const block of src.split('@font-face').slice(1)) {
    const subset = (block.match(/\/\* nunito-([a-z-]+)-\d+-normal \*\//) ?? [])[1];
    if (!subset || !/^latin/.test(subset)) continue;
    const woff2 = (block.match(/url\(\.\/files\/([^)]+\.woff2)\)/) ?? [])[1];
    const range = (block.match(/unicode-range:\s*([^;]+);/) ?? [])[1];
    css += `@font-face{font-family:'Nunito';font-style:normal;font-display:swap;font-weight:${w};src:url(../../node_modules/@fontsource/nunito/files/${woff2}) format('woff2');unicode-range:${range.trim()};}\n`;
  }
}

const jp = [
  ['Klee One', 400, 'klee-one-400.woff2'],
  ['Shippori Mincho B1', 700, 'shippori-mincho-b1-700.woff2'],
  ['M PLUS Rounded 1c', 400, 'm-plus-rounded-1c-400.woff2'],
  ['M PLUS Rounded 1c', 700, 'm-plus-rounded-1c-700.woff2'],
];
for (const [family, weight, file] of jp) {
  css += `@font-face{font-family:'${family}';font-style:normal;font-display:swap;font-weight:${weight};src:url(./fonts/${file}) format('woff2');}\n`;
}

writeFileSync(outFile, css);
console.log('fonts.generated.css written');
